# Generated by Django 5.0.6 on 2024-06-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
