# Generated by Django 5.0.6 on 2024-06-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_alter_animalproducto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalproducto',
            name='minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animalproducto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='animalproducto',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
