# Generated by Django 5.0.6 on 2024-06-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='producto_gato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animales.productogatos'),
        ),
    ]
