# Generated by Django 5.0.6 on 2024-06-26 15:46

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    # Obtén los modelos
    Carrito = apps.get_model('yourappname', 'Carrito')
    ProductoPerros = apps.get_model('yourappname', 'ProductoPerros')
    ProductoGatos = apps.get_model('yourappname', 'ProductoGatos')
    AnimalProducto = apps.get_model('yourappname', 'AnimalProducto')

    # Transfiere los datos del campo producto a los nuevos campos
    for item in Carrito.objects.all():
        if item.producto:
            if ProductoPerros.objects.filter(nombre=item.producto.nombre).exists():
                item.producto_perros = ProductoPerros.objects.get(nombre=item.producto.nombre)
            elif ProductoGatos.objects.filter(nombre=item.producto.nombre).exists():
                item.producto_gatos = ProductoGatos.objects.get(nombre=item.producto.nombre)
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0010_carrito_producto_gatos_carrito_producto_perros_and_more'),
    ]

    operations = [
    ]
